package com.android.ql.lf.redpacketmonkey.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.android.ql.lf.redpacketmonkey.data.greendao.RedPacketBean;

import com.android.ql.lf.redpacketmonkey.greendao.RedPacketBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig redPacketBeanDaoConfig;

    private final RedPacketBeanDao redPacketBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        redPacketBeanDaoConfig = daoConfigMap.get(RedPacketBeanDao.class).clone();
        redPacketBeanDaoConfig.initIdentityScope(type);

        redPacketBeanDao = new RedPacketBeanDao(redPacketBeanDaoConfig, this);

        registerDao(RedPacketBean.class, redPacketBeanDao);
    }
    
    public void clear() {
        redPacketBeanDaoConfig.clearIdentityScope();
    }

    public RedPacketBeanDao getRedPacketBeanDao() {
        return redPacketBeanDao;
    }

}
